ansible_become_pass: ENC[AES256_GCM,data:nwZTSM6p+nuPmJ1Sf6+gK323,iv:1XVmwmN+5CG8q9xkTfBT8mLsl3ULWm5lj1Gs+ksp3TA=,tag:HRNTyjeiMdlTwxDVS6801A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yzp6s7gjc9y80c9jawlmn7f4ajkxuulr02ysqq7fpx5qct6eeeasakap8j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobVlsSk05YlRFWUJoRkE3
            RUdQZU1nYThzUitnUTBXM0prNkFJOXdEbUhRClVwMnVtdXNMVDQ3N295WGdKY3h6
            bmhVVzVlYUlSM2k1OVRMdVdHRHBRVkEKLS0tIHFxZEVTdW10dUlyN1VhS1d6bUM5
            ejdackhNb3ROM2RLekw2OUowaFNTQlEKhn3SMZxKL2g/g8po3xAVNn85Gx1+2QGN
            DuEsym6+tPR7EUs8GLD5ceIsYCqzS18I8e5vroJcMvuW4smRdv+a0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T17:44:17Z"
    mac: ENC[AES256_GCM,data:SSR64WaUjbeHnu908oJbD00RAvzpBl7NcAlmgh9meU/XPt5brQKXVT1G7XZCmHc7iv5kcaD/uKKQqXopO5o4F8pAuucTjy1cEq7gdeKGsuQDG2Dko7GLrxxrsIfH6i6/zW7cLecio7vizGOU1Mjd4aV0ccBPosp6JXF2irqyiA4=,iv:RG7GBXoEvo6jJviZx62eiIfrdvDGy1jUfp2jRq2Rdlc=,tag:QXctLf0h+1LK4E1/f8d54Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
