apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yzp6s7gjc9y80c9jawlmn7f4ajkxuulr02ysqq7fpx5qct6eeeasakap8j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUWVJOHpDMm91RGFTMFNE
            VE12c2tTSk1LY0czNmNIVVdadHUyUk11MEdNCmR5UHV4WEozRE5IaUhUQ2k5SFFa
            VWxuc2tGVzF4V0xnUHFmLzJYRVUrZDAKLS0tIGE2ZXFEYk9uWDNKbkVXZXZwdCtr
            NHk3T0dwamF2ZUpjeDY5T0VuWUlXT2cKVejLtaDtzE6MFcbNbZgj5ySM1tw0znZ2
            /nvsXfja4XPCkunJlKHPI2OzM4mMaIr3fGdZyu/NygormwNnX+l9Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:30:14Z"
    mac: ENC[AES256_GCM,data:NgSalUu791+NF7LxIinI4USQhPhFKyhmsPgfYpRlzuTddrRquqlgUiwdDWrgPDocHs8rlpvgXLUzbnLYDxyrGZVGDaNEPhIbNd1ddoIUZCUwggJCTDA4/n5xDIQdip1eaZQfg9WuCYL638hHwS64FcIuyrXrKKAAFGeujoUFKYU=,iv:XlJXQkgQDOEV/Ae4DXrznwG573DhaI4u40bERZyieLI=,tag:BqJeaigGSsAprxhtjIjflQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
