apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:unly0jl24Ad/atGuqLnUh/UqiEB43K2K4RLcDkA4nkVywWpqeI4eRA==,iv:BAOf3HVDwv8tHtAyNxRGjqdtqKsjZjljOcsGt/rPqhw=,tag:Jr/9bVzWbJLtLJd6kVZj9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yzp6s7gjc9y80c9jawlmn7f4ajkxuulr02ysqq7fpx5qct6eeeasakap8j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQWlINHVVbFh1NEkyZStY
            VmhKejVjNHd0WHEyMzRlcXg2STJNSGNSRlNnCiswU2RiWW9VeWgvYktEcGwzUGVF
            Nk5kVjF2OWdpRVdpcjlGSDJaMUwvR0kKLS0tIGhkbGdKNmxPVzVzQkxVVkNPY0FD
            aXVNUUdBOXYyQzdPcnR3d09YWlRvTWMKbRQL1kV6c8xZs5ZfeNBf0VDj0SElkKgb
            N+guY7dwKjf0cggbAw02AUqALlw3TDqqJkWnW/hQDZ4hm79yITArsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T19:59:22Z"
    mac: ENC[AES256_GCM,data:yUmTNFVEH5uAlt5z2UprIlXzLHT/kVu8JJeEglNSmCf8mSUsayxfJfl5KQfEdtQM6F4VXzNTgQAfDoVeF9+jZlrp3W/NcL6f8ABAsdJQaiOaPoufyQrOwWbFSlsi41neV02K2DqJNHSWkjva+XSQMzX1tfhowJTjSjInOgQTAeQ=,iv:Ve+rVABIfth4fYUIqb4w7XfMtiEsOEQCpJx2i388Rmc=,tag:5SAtXTIpzV7f/0bdqTIYEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
