apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:KmjwQuJVaEYF3xhJBrkK8MsP4kQA,iv:ptlJQedqlTRgjI4hztApXiZHBVORXD73aXrlBWzedsE=,tag:/MI/qRFGtkp63gKCaqqcSQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:PEFqVf/T1B2NIGp2pYWkYjtRyI674WBZCUdmNhl3ucGowM13,iv:MLy/qaKHhTJX9oXtSg22rC3sR3Bg9fnFRcYYUUL7cnE=,tag:+C0IbXQ0X4LONk2Yr1/63g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:WoH91BQ1RmW2tHkG,iv:DcCQkb0H2C5kSutfu6sXU1Tk1N4Xy3kNOTYGSpdPcUY=,tag:w4G5Y0EOfBCHBn7sBxRb6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yzp6s7gjc9y80c9jawlmn7f4ajkxuulr02ysqq7fpx5qct6eeeasakap8j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4clRCaU50NnF3N1Bxc2px
            TUU1NTdONHpZL2NZdDhqQXhSSkl6SUxhRXlzCk9wRHoyQzkxTHBOSnpaOTZNOUJI
            Q2UzK09VaWNLWGQyT1ozSCs1LzZuMkUKLS0tIDhKQW1BU0hkdXFlelN0aFVjZnFv
            NURySUdaNmhzbFg3OC9CbVI4bGNqODgKrR1VanYmoQmhRLOTpM2R8sQNg0WKR7II
            +Xfu0FxiiTmwQqHCt43+I44yapC6c7gqlkP6d2J1lmvcZgtnZfD1CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T19:59:23Z"
    mac: ENC[AES256_GCM,data:LlSKla+r8ICUlHujdr0hi/Vuys/Db2YFa0ZvV+2Q+Mht0twPr0Y7BaxZI8EVPvdx/bQlNWIRQbh8yc43URaZYHclMzUJEpIo57AXf6WBqJ/iTPMuMwej1Bx8AGXgP5o+mlvX6RStw5/Rma5AF7D/L9iWYasAJoq6TdyTdqkMYX0=,iv:6RvB8/cP2h9WRGzYiAqAvCKuUQFomPkfgGiTczcrgLQ=,tag:2+MOauoSidpEgOGVj29Ziw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
